name: app_activity

on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  extract_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium==4.17.2
          
      - run: python app_activity.py
